Controllers/CTMasterController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DTVSystem.Controllers
{
    public class CTMasterController : Controller
    {
        public IActionResult MAS0010()
        {
            //Filter
            List<SelectListItem> ddlFactoryName = new()
            {
                new SelectListItem { Value = "1", Text = "Factory1" },
                new SelectListItem { Value = "2", Text = "Factory2" },

            };
            List<SelectListItem> ddlLine = new()
            {
                new SelectListItem { Value = "1", Text = "Line name 1" },
                new SelectListItem { Value = "2", Text = "Line name 2" },
                new SelectListItem { Value = "3", Text = "Line name 3" },

            };

            ViewBag.DDlFactory = ddlFactoryName;
            ViewBag.DDlLine = ddlLine;

            return View();
        }
    }
}

Controllers/SampleController.cs
using Microsoft.AspNetCore.Mvc;
using Npgsql;
using System.Data;
using DTVSystem.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DTVSystem.Controllers
{
    public class SampleController : Controller
    {
        public IActionResult SAM0001()
        {
            SAM0001ViewModel model = new SAM0001ViewModel();
            model.Title = "SAM0001 : Component";

            model.Mode = "Add";
            model.CreateInfo = "Create Data.";
            model.UpdateInfo = "Update Data.";

            List<SelectListItem> lstDdlCustomer = new List<SelectListItem>();
            SelectListItem item = new SelectListItem
            {
                Text = "Text1",
                Value = "A001",
            };
            lstDdlCustomer.Add(item);
            model.CustomerListItem = lstDdlCustomer;

            return View(model);
        }

        public IActionResult SAM0010()
        {
            SAM0010ViewModel model = new SAM0010ViewModel();
            model.Title = "SAM0010 : Mas_Company";

            model.Mode = "Add";
            model.CreateInfo = "Create Data.";
            model.UpdateInfo = "Update Data.";

            List<SelectListItem> lstDdlCustomer = new List<SelectListItem>();
            SelectListItem item = new SelectListItem
            {
                Text = "Text1",
                Value = "A001",
            };
            lstDdlCustomer.Add(item);
            model.CompanyModel = new Models.CompanyModel();
            model.CompanyModel.Company_ID = 1;
            model.CompanyModel.Company_name = "DIT";

            model.CompanyModelList = new List<Models.CompanyModel>();
            model.CompanyModelList.Add(model.CompanyModel);

            return View(model);
        }

        public async Task<IActionResult> SAM0011()
        {
            return View();
        }

        [HttpPost]
        public Boolean Save1()
        {
            Boolean result = false;

            return result;
        }

        [HttpPost]
        public JsonResult AjaxMethod()
        {
            return Json("OK");
        }

        //public IActionResult SAM0011()
        //{
        //    SAM0010ViewModel model = new SAM0010ViewModel();
        //    model.Title = "SAM0010";

        //    model.Mode = "Add";
        //    model.CreateInfo = "Create Data.";
        //    model.UpdateInfo = "Update Data.";

        //    List<SelectListItem> lstDdlCustomer = new List<SelectListItem>();
        //    SelectListItem item = new SelectListItem
        //    {
        //        Text = "Text1",
        //        Value = "A001",
        //    };
        //    lstDdlCustomer.Add(item);
        //    //model.CustomerListItem = lstDdlCustomer;

        //    return View(model);
        //}

        public IActionResult PatternList()
        {
            #region Pattern1

            ////string sqlData = _configuration.GetConnectionString("DefaultConnection");
            //string sqlData = "Server=192.168.10.89;Port=5432;User Id=dtvuser;Password=abc123$1;Database=dtvdb";
            //Npgsql.NpgsqlConnection conn = new Npgsql.NpgsqlConnection(sqlData);
            //conn.Open();
            //Npgsql.NpgsqlCommand comm = new Npgsql.NpgsqlCommand();
            //comm.Connection = conn;
            //comm.CommandType = System.Data.CommandType.Text;
            //comm.CommandText = "select * from test";

            ////comm.CommandText = "select * from Department where DepartmentId = @Departmentid";
            ////comm.Parameters.AddWithValue("@Departmentid", id);

            ////var dept = new Department();

            //Npgsql.NpgsqlDataReader sdr = comm.ExecuteReader();
            //while (sdr.Read())
            //{
            //    int i = Convert.ToInt32(sdr["code"]);
            //    string text = (string)sdr["name"];

            //    //dept.DepartmentId = Convert.ToInt32(sdr["DepartmentId"]);
            //    //dept.DepartmentName = sdr["DepartmentName"].ToString();

            //}

            #endregion


            #region Pattern2

            //string strExceptionMsg = "";

            //#region Npgsql
            //NpgsqlConnection conn;
            //conn = new NpgsqlConnection("Server=192.168.10.89;Port=5432;User Id=dtvuser;Password=abc123$1;Database=dtvdb");

            //try
            //{
            //    conn.Open();
            //}
            //catch (NpgsqlException)
            //{
            //    strExceptionMsg = "CouldntOpenConn";
            //    conn.Close();
            //}
            //catch (System.IO.IOException)
            //{
            //    strExceptionMsg = "ConnClosed";
            //    conn.Close();
            //}
            //#endregion

            //string sql = "SELECT code, name FROM test ORDER BY code";

            //NpgsqlDataAdapter da = new NpgsqlDataAdapter(sql, conn);
            //DataTable dt = new DataTable();
            //da.Fill(dt);
            //if (dt.Rows.Count == 0)
            //{
            //    conn.Close();
            //    strExceptionMsg = "No data";
            //}
            //else
            //{
            //    DataRow row = dt.Rows[0];
            //    strExceptionMsg = row["name"].ToString();
            //    conn.Close();
            //}

            #endregion


            #region Pattern3

            string strExceptionMsg = "";
            
            NpgsqlConnection conn = new NpgsqlConnection();

            try
            {
                //conn.ConnectionString = "Server=192.168.10.89;Port=5432;User Id=dtvuser;Password=abc123$1;Database=dtvdb";
                conn.ConnectionString = "Server=::1;Port=5433;User Id=dtvuser;Password=abc123$1;Database=dtvdb";
                //command
                string sql = "SELECT code, name FROM test ORDER BY code";
                conn.Open();
                NpgsqlDataAdapter da = new NpgsqlDataAdapter(sql, conn);
                DataTable dt = new DataTable();
                da.Fill(dt);
                if (dt.Rows.Count == 0)
                {
                    
                    strExceptionMsg = "No data";
                }
                else
                {
                    DataRow row = dt.Rows[0];
                    strExceptionMsg = row["name"].ToString();
                }
            }
            catch (NpgsqlException ex)
            {
                throw new Exception(ex.Message);
            }
            catch (Exception ex)
            {
                throw new Exception(ex.Message);
            }
            finally
            {
                conn.Close();
            }
            #endregion

            return View();
        }
    }
}


//SqlConnection cn = new SqlConnection();
//try
//{
//    cn.ConnectionString = Academia.Model.Dao.Dados.Model_Dao_Dados.getStringDeConexao();
//    //command
//    SqlCommand cmd = new SqlCommand();
//    cmd.Connection = cn;
//    cmd.CommandText = "insert into produto(descricao,unidade,estoque,valordevenda,observacao) values (@descricao,@unidade,@estoque,@valordevenda,@observacao);";
//    cmd.Parameters.AddWithValue("@descricao", pProduto.Descricao);
//    cmd.Parameters.AddWithValue("@unidade", pProduto.Unidade);
//    cmd.Parameters.AddWithValue("@estoque", pProduto.Estoque);
//    cmd.Parameters.AddWithValue("@valordevenda", pProduto.ValorDeVenda);
//    cmd.Parameters.AddWithValue("@observacao", pProduto.Observacao);
//    cn.Open();
//    pProduto.Id = Convert.ToInt32(cmd.ExecuteScalar());
//}
//catch (SqlException ex)
//{
//    throw new Exception("Servidor SQL Erro:" + ex.Number);
//}
//catch (Exception ex)
//{
//    throw new Exception(ex.Message);
//}
//finally
//{
//    cn.Close();
//}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplicationCore1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DTVSystem.styles.css" asp-append-version="true" />

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>

     @*script navbar menu*@
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
</head>
<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
<body style="background-color:black;">
    <header>
        @*date, humidity, temperature*@
        <nav class="navbar navbar-expand-lg navbar-dark bg-white">
            <div class="col-6 text-start">
                <span>
                    <img src="~/Image/Untitled.png" alt="Dev 2 System" height="25" />
                    <b>Digital twin visualization system (DTV)</b>
                </span>
            </div>
            <span class="col-6 text-end">
                80 %
                <img src="~/Image/humidity.png" alt="Dev 2 System" height="15" />
                29 °C
                <img src="~/Image/icons8-temperature-80.png" alt="Dev 2 System" height="15" />
                <span class="" id='date-time'></span>
            </span>
        </nav>
        @* navbar menu multi level *@
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand mr-5 menuHome" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-home" style="font-size:30px;color:red"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main_nav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="main_nav">
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown" id="myDropdown">
                            <a class="nav-link dropdown-toggle mr-5" data-bs-toggle="dropdown"><i class="fab fa-delicious"></i> Monitoring  </a>
                            <ul class="dropdown-menu">
                                <li> <a class="dropdown-item AddColor" asp-area="" asp-controller="ProductionResultAll" asp-action="ProductionResultAll"> Production Result (all assembly lines)</a></li>
                                <li>
                                    <a class="dropdown-item" href="#"> Staff attendance monitoring <span> &rtrif; </span> </a>
                                    <ul class="dropdown-submenu dropdown-menu" id="DDLStaff">
                                    </ul>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="#"> Machine down time analysis (Real-time) <span> &rtrif; </span> </a>
                                    <ul class="dropdown-submenu dropdown-menu" id="DDLMachine">
                                    </ul>
                                </li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown" id="myDropdown2">
                            <a class="nav-link dropdown-toggle mr-5" data-bs-toggle="dropdown"><i class="fab fa-delicious"></i>  History Analysis  </a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a class="dropdown-item" href="#"> Production Leadtime <span> &rtrif; </span> </a>
                                    <ul class="dropdown-submenu dropdown-menu">
                                        <li><a class="dropdown-item" href="#">Submenu item 1</a></li>
                                        <li><a class="dropdown-item" href="#">Submenu item 2</a></li>
                                    </ul>
                                </li>
                                <li><a class="dropdown-item" href="#"> KPI Summary by line </a></li>
                                <li><a class="dropdown-item" href="#"> Cycle time (Mode) </a></li>
                                <li><a class="dropdown-item" href="#"> Takt Balance </a></li>
                                <li><a class="dropdown-item" href="#"> Loss time </a></li>
                            </ul>
                        </li>
                        <li class="nav-item dropdown" id="myDropdown2">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fab fa-delicious"></i>  Master Data  </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item AddColor" asp-area="" asp-controller="CTMaster" asp-action="MAS0010"> C/T Master </a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
                    <ul class="navbar-nav text-right">
                        <li class="nav-item topnav-right dropdown" id="myDropdown2">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown"> User ID: xxxx <i class="fas fa-user"></i> </a>
                            <ul class="dropdown-menu dropdown-menu-lg-end">
                                <li><a class="dropdown-item" href="#"> User Name: [Firstname] [Lastname] </a></li>
                                <li><button class="btn btn-primary">Logout</button></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <nav class="navbar navbar-expand-lg navbar-dark bg-danger navbarline">

        </nav>
    </header>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="modal" tabindex="-1" id="form-modal-Error">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <i class="fas fa-exclamation-triangle me-3" style="color:red;font-size:30px;"></i>
                    <h3 class="modal-title"></h3>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="text-align:center;">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-success col-3" data-bs-dismiss="modal"><i class="fas fa-check"></i>OK</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="form-modal-Infomation">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <i class="fas fa-exclamation-triangle me-3" style="color:#F2E135;font-size:30px;"></i>
                    <h3 class="modal-title"></h3>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary col-3 me-2" data-bs-dismiss="modal" onclick="ClickConfirm()"><i class="fas fa-check"></i>Confirm</button>
                    <button type="button" class="btn btn-danger col-3" data-bs-dismiss="modal"><i class="fas fa-times"></i>Cancel</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="form-modal-Warining">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title"></h3>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" style="text-align:center;">
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">OK</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal" tabindex="-1" id="form-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title"></h5>
                    <button type="button" class="btn-close hide" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                </div>
                @*<div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                    </div>*@
            </div>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplicationCore1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            <a asp-area="" asp-controller="Sample" asp-action="PatternList">PatternList</a>
            <a asp-area="" asp-controller="Sample" asp-action="SAM0001">SAM0001</a>
            <a asp-area="" asp-controller="Sample" asp-action="SAM0010">SAM0010</a>
        </div>

    </footer>

</body>
</html>

<script>
     $(document).ready(function () {
             for(var i = 0; i<4;i++)
             {
                 // genarate multi level
                 $('#DDLStaff').append('<li>'+
                                     '<a class="dropdown-item AddColor" href="#">Factory'+i+'<span> &rtrif; </span> </a>'+
                                     '<ul class="dropdown-submenu AddBgColor dropdown-menu" id="detailFactoryStaff'+i+'">'+
                                     '</ul>'+
                                     '</li>');

                 $('#DDLMachine').append('<li>'+
                                     '<a class="dropdown-item AddColor" href="#">Factory'+i+'<span> &rtrif; </span> </a>'+
                                     '<ul class="dropdown-submenu AddBgColor dropdown-menu" id="detailFactoryMachine'+i+'">'+
                                     '</ul>'+
                                     '</li>');
             }
             for(var n = 0; n<4;n++)
             {
                 var idFacStaff = "detailFactoryStaff"+n
                 var idFacMac = "detailFactoryMachine"+n
                 for(var j = 0; j < 6 ; j++)
                 {
                     // genarate multi level
                     $('#'+idFacStaff).append('<li><a class="dropdown-item AddColor"  href="/Home/Privacy">Detail_'+j+'</a></li>');
                     $('#'+idFacMac).append('<li><a class="dropdown-item AddColor" href="/MachineDownTimeAnalysis/MCD0010">Detail_'+j+'</a></li>');
                 }
             }



     });

     //get date, time
     var timeDisplay = document.getElementById("date-time");

     function refreshTime() {
         var dateString = new Date().toLocaleString("th-TH");
         timeDisplay.innerHTML = dateString;

     }

     setInterval(refreshTime, 1000);

  
</script>