Controllers/MachineDownTimeAnalysisController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DTVSystem.Controllers
{
    public class MachineDownTimeAnalysisController : Controller
    {
        public IActionResult MCD0010()
        {
            //Filter
            List<SelectListItem> ddlFactoryName = new()
            {
                new SelectListItem { Value = "1", Text = "Factory1" },
                new SelectListItem { Value = "2", Text = "Factory2" },

            };
            List<SelectListItem> ddlLine = new()
            {
                new SelectListItem { Value = "1", Text = "Line name 1" },
                new SelectListItem { Value = "2", Text = "Line name 2" },
                new SelectListItem { Value = "3", Text = "Line name 3" },

            };
            List<SelectListItem> ddlProcess = new()
            {
                new SelectListItem { Value = "1", Text = "Process name 1" },
                new SelectListItem { Value = "2", Text = "Process name 2" },
                new SelectListItem { Value = "3", Text = "Process name 3" },
                new SelectListItem { Value = "4", Text = "Process name 4" },

            };
            List<SelectListItem> ddlMachineG = new()
            {
                new SelectListItem { Value = "1", Text = "MachineG name 1" },
                new SelectListItem { Value = "2", Text = "MachineG name 2" },
                new SelectListItem { Value = "3", Text = "MachineG name 3" },
                new SelectListItem { Value = "4", Text = "MachineG name 4" },

            };
            List<SelectListItem> ddlMachine = new()
            {
                new SelectListItem { Value = "1", Text = "Machine name 1" },
                new SelectListItem { Value = "2", Text = "Machine name 2" },
                new SelectListItem { Value = "3", Text = "Machine name 3" },
                new SelectListItem { Value = "4", Text = "Machine name 4" },

            };

            ViewBag.DDlFactory = ddlFactoryName;
            ViewBag.DDlLine = ddlLine;
            ViewBag.DDlProcess = ddlProcess;
            ViewBag.DDlMachineG = ddlMachineG;
            ViewBag.DDlMachine = ddlMachine;

            return View();
        }

        [HttpPost]
        public ActionResult getSearch()
        {
            string lstdata = null;
            return Json(new { data = lstdata ,status = false});
        }
    }
}

Views/MachineDownTimeAnalysis/MCD0010.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


<style>
    #DDlMachineG[disabled] {
        background-color: lightgrey;
    }

    .reqDDL{
        border-color : red;
    }

    .center {
        text-align: center;
        font-size:60px;
        color:white;
        margin-top: 10%;
        margin-left: 35%;
    }

</style>

@*search*@
<div class="">
    <div class="panel" id="fieldSearch" style="background-color:lightgray;">
        <div class="panel-body form-horizontal">
            <div class="row">
                <label class="col-md-3">Machine Downtime Analysis Realtime</label>
                <div class="col-md-2">
                    <label class="me-4">Type</label>
                    <input type="radio" class="me-1" name="machineT" value="1" checked>Machine &nbsp;
                    <input type="radio" class="me-1" name="machineT" value="2">Machine group
                </div>
                <div class="row col-md-2">
                    <label style="width:30%">Factory<span class="text-danger" id="spanreqDDlFactory">*</span></label>
                    <select id="DDlFactory" class="form-control" style="width:60%!important;" asp-items="@ViewBag.DDlFactory">
                        <option></option>
                    </select>
                </div>
                <div class="row col-md-2">
                    <label style="width:30%">Line<span class="text-danger" id="spanreqDDlLine">*</span></label>
                    <select id="DDlLine" class="form-control" style="width:60%" asp-items="@ViewBag.DDlLine">
                        <option></option>
                    </select>
                </div>
                <div class="row col-md-2">
                    <label style="width:30%">Process<span class="text-danger" id="spanreqDDlProcess">*</span></label>
                    <select id="DDlProcess" class="form-control" style="width:60%" asp-items="@ViewBag.DDlProcess">
                        <option></option>
                    </select>
                </div>
            </div>
            <div class="offset-5 mt-2">
                <div class="row col-md-4">
                    <label style="width:40%">Machine Group<span class="text-danger" id="spanreqDDlMachineG">*</span></label>
                    <select id="DDlMachineG" class="form-control" style="width:55%" asp-items="@ViewBag.DDlMachineG">
                        <option></option>
                    </select>
                </div>
                <div class="row col-md-4">
                    <label style="width:30%">Machine</label>
                    <select id="ddlMachine" class="form-control" style="width:55%" asp-items="@ViewBag.ddlMachine">
                        <option></option>
                    </select>
                </div>
                <button class="btn btn-light col-md-1 me-2" onclick="ClickSearch()"><i class="fas fa-search" style="color:green;"></i> Search</button>
                <button class="btn btn-light col-md-1" onclick="ClickClear()"><i class="fas fa-times" style="color:red;"></i> Clear</button>
            </div>

        </div>
    </div>
</div>
@*display*@
<div>
    <label class="center" id="ErrMessage" ></label>
</div>

<script>
    $(document).ready(function () {
        //set display [*]
        document.getElementById("spanreqDDlFactory").classList.remove("hide");
                document.getElementById("spanreqDDlLine").classList.remove("hide");
                document.getElementById("spanreqDDlProcess").classList.remove("hide");
                document.getElementById("spanreqDDlMachineG").classList.add("hide");
                document.getElementById("DDlMachineG").disabled = true;

        $('input[type=radio][name=machineT]').change(function() {
            if (this.value == "1") // choose Machine
            {
                document.getElementById("spanreqDDlFactory").classList.remove("hide"); //show
                document.getElementById("spanreqDDlLine").classList.remove("hide");    //show
                document.getElementById("spanreqDDlProcess").classList.remove("hide"); //show
                document.getElementById("spanreqDDlMachineG").classList.add("hide");   //hide
                document.getElementById("DDlMachineG").disabled = true;                //disable

            }
            else if (this.value == "2") // choose Machine group
            {
                document.getElementById("spanreqDDlFactory").classList.add("hide");     //hide
                document.getElementById("spanreqDDlLine").classList.add("hide");        //hide
                document.getElementById("spanreqDDlProcess").classList.add("hide");     //hide
                document.getElementById("spanreqDDlMachineG").classList.remove("hide"); //show
                document.getElementById("DDlMachineG").disabled = false;                //enable
            }
        });
    });

    function ClickClear(){
        location.href = '@Url.Action("MCD0010", "MachineDownTimeAnalysis")'
    }

    function ClickSearch(){
        counterr = 0
        var fieldEmpty = "";
        var val_radio = document.querySelector('input[name="machineT"]:checked').value;
        //check data require
        if(val_radio == "1") // choose Machine
        {
            if($("#DDlFactory").val() == "")
            {
                fieldEmpty = fieldEmpty + "Factory"
                counterr++
            }
            else
            {
            }
            if($("#DDlLine").val() == "")
            {
                if(fieldEmpty != "")
                {
                    fieldEmpty = fieldEmpty + ", "
                }
                fieldEmpty = fieldEmpty + "Line"
                counterr++
            }
            else
            {
            }
            if($("#DDlProcess").val() == "")
            {
                if(fieldEmpty != "")
                {
                    fieldEmpty = fieldEmpty + ", "
                }
                fieldEmpty = fieldEmpty + "Process"

                counterr++
            }
            else
            {
            }
        }
        else // choose Machine group
        {
            if($("#DDlMachineG").val() == "")
            {
                fieldEmpty = fieldEmpty + "Machine Group"
                counterr++
            }
            else
            {
            }

        }

        if(counterr == 0) // don't have error
        {
            $.ajax({
                type: "POST",
                url: '@Url.Action("getSearch", "MachineDownTimeAnalysis")',
                data: {
                    id: $("#EmpPosReqId").val(),
                },
                dataType: 'json',
                success: function (data) {
                    if (!data.status) {
                        $("#ErrMessage").html("Data does not exist")
                        return;
                    }
                    document.getElementById("ErrMessage").classList.remove("center");
                }
            });
        }
        else // have error
        {
            fieldEmpty = fieldEmpty + " should not be empty"

            ShowError('Error Message', fieldEmpty );
        }

    }
</script>

Views/MachineDownTimeAnalysis/pageInitial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    #DDlMachineG[disabled] {
        background-color: lightgrey;
    }

    .reqDDL{
        border-color : red;
    }

    .center {
        text-align: center;
        font-size:60px;
        color:white;
        margin-top: 10%;
        margin-left: 35%;
    }
</style>

<div class="">
    <div class="panel" id="fieldSearch" style="background-color:lightgray;">
        <div class="panel-body form-horizontal">
            <div class="row">
                <label class="col-md-3">Machine Downtime Analysis Realtime</label>
                <div class="col-md-2">
                    <label class="me-4">Type</label>
                    <input type="radio" class="me-1" name="machineT" value="1" checked>Machine &nbsp;
                    <input type="radio" class="me-1" name="machineT" value="2">Machine group
                </div>
                <div class="row col-md-2">
                    <label style="width:30%">Factory<span class="text-danger" id="spanreqDDlFactory">*</span></label>
                    <select id="DDlFactory" class="form-control" style="width:60%" asp-items="@ViewBag.DDlFactory">
                        <option></option>
                    </select>
                </div>
                <div class="row col-md-2">
                    <label style="width:30%">Line<span class="text-danger" id="spanreqDDlLine">*</span></label>
                    <select id="DDlLine" class="form-control" style="width:60%" asp-items="@ViewBag.DDlLine">
                        <option></option>
                    </select>
                </div>
                <div class="row col-md-2">
                    <label style="width:30%">Process<span class="text-danger" id="spanreqDDlProcess">*</span></label>
                    <select id="DDlProcess" class="form-control" style="width:60%" asp-items="@ViewBag.DDlProcess">
                        <option></option>
                    </select>
                </div>
            </div>
            <div class="offset-5 mt-2">
                <div class="row col-md-4">
                    <label style="width:40%">Machine Group<span class="text-danger" id="spanreqDDlMachineG">*</span></label>
                    <select id="DDlMachineG" class="form-control" style="width:55%" asp-items="@ViewBag.DDlMachineG">
                        <option></option>
                    </select>
                </div>
                <div class="row col-md-4">
                    <label style="width:30%">Machine</label>
                    <select id="ddlMachine" class="form-control" style="width:55%" asp-items="@ViewBag.ddlMachine">
                        <option></option>
                    </select>
                </div>
                <button class="btn btn-light col-md-1 me-2" onclick="ClickSearch()"><i class="fas fa-search" style="color:green;"></i> Search</button>
                <button class="btn btn-light col-md-1" onclick="ClickClear()"><i class="fas fa-times" style="color:red;"></i> Clear</button>
            </div>

        </div>
    </div>
</div>
<div>
    <label class="center" id="ErrMessage" ></label>
</div>

<script>
    $(document).ready(function () {
        document.getElementById("spanreqDDlFactory").classList.remove("hide");
                document.getElementById("spanreqDDlLine").classList.remove("hide");
                document.getElementById("spanreqDDlProcess").classList.remove("hide");
                document.getElementById("spanreqDDlMachineG").classList.add("hide");
                document.getElementById("DDlMachineG").disabled = true;

        $('input[type=radio][name=machineT]').change(function() {
            if (this.value == "1")
            {
                document.getElementById("spanreqDDlFactory").classList.remove("hide");
                document.getElementById("spanreqDDlLine").classList.remove("hide");
                document.getElementById("spanreqDDlProcess").classList.remove("hide");
                document.getElementById("spanreqDDlMachineG").classList.add("hide");
                document.getElementById("DDlMachineG").disabled = true;

            }
            else if (this.value == "2")
            {
                document.getElementById("spanreqDDlFactory").classList.add("hide");
                document.getElementById("spanreqDDlLine").classList.add("hide");
                document.getElementById("spanreqDDlProcess").classList.add("hide");
                document.getElementById("spanreqDDlMachineG").classList.remove("hide");
                document.getElementById("DDlMachineG").disabled = false;
            }
        });
    });

    function ClickClear(){
        location.href = '@Url.Action("pageInitial", "MachineDownTimeAnalysis")'
    }

    function ClickSearch(){
        counterr = 0
        var val_radio = document.querySelector('input[name="machineT"]:checked').value;
        if(val_radio == "1")
        {
            if($("#DDlFactory").val() == "")
            {
                document.getElementById("DDlFactory").style.borderWidth = "3px"
                document.getElementById("DDlFactory").style.borderColor = "red"
                counterr++
            }
            else
            {
                document.getElementById("DDlFactory").style.borderWidth = ""
                document.getElementById("DDlFactory").style.borderColor = ""
            }
            if($("#DDlLine").val() == "")
            {
                document.getElementById("DDlLine").style.borderWidth = "3px"
                document.getElementById("DDlLine").style.borderColor = "red"
                counterr++
            }
            else
            {
                document.getElementById("DDlLine").style.borderWidth = ""
                document.getElementById("DDlLine").style.borderColor = ""
            }
            if($("#DDlProcess").val() == "")
            {
                document.getElementById("DDlProcess").style.borderWidth = "3px"
                document.getElementById("DDlProcess").style.borderColor = "red"
                counterr++
            }
            else
            {
                document.getElementById("DDlProcess").style.borderWidth = ""
                document.getElementById("DDlProcess").style.borderColor = ""
            }
        }
        else
        {
            if($("#DDlMachineG").val() == "")
            {
                document.getElementById("DDlMachineG").style.borderWidth = "3px"
                document.getElementById("DDlMachineG").style.borderColor = "red"
                counterr++
            }
            else
            {
                document.getElementById("DDlMachineG").style.borderWidth = ""
                document.getElementById("DDlMachineG").style.borderColor = ""
            }

        }

        if(counterr == 0)
        {
            $.ajax({
                type: "POST",
                url: '@Url.Action("getSearch", "MachineDownTimeAnalysis")',
                data: {
                    id: $("#EmpPosReqId").val(),
                },
                dataType: 'json',
                success: function (data) {
                    if (!data.status) {
                        $("#ErrMessage").html("Data does not exist")
                        return;
                    }
                    document.getElementById("ErrMessage").classList.remove("center");
                }
            });
        }

    }
</script>